### ISSUE TITLE
Wants to open app store instead of Square App

### ISSUE THREAD

**Issue by spycedev** [ProteanSoftware/capacitor-square#2]
Behavior: When .startTransaction is called the device wants to open square in the play store. Square POS is already installed.

Expected Behavior: Open square app with provided parameters.

Not sure if I'm missing a step to get this to work?

**Comment by AshleyMedway** [comment]
Can you share your calling code?

**Comment by spycedev** [comment]
Yep, I just copied the example code. Sorry, I'm brand new to capacitor and we're switching from Cordova solely because this plugin exists :)

![code](https://user-images.githubusercontent.com/83834054/170573395-6614c433-d49d-4751-ba45-4885e4fbef7d.png)

**Comment by spycedev** [comment]
I'm not sure if this matters, but do I have to have my app package name and sha-1 fingerprint setup in the square dashboard for it to open the square app instead of the app store?

**Comment by AshleyMedway** [comment]
Can you try adding a couple of things to see if you get anything in the output?

```ts
CapacitorSquare.initApp({
  applicationId: "sq0idp-xxxxxxxxx"
}).then(() => {
  console.log("working");
}).catch(e => {
  console.error(e);
});

CapacitorSquare.addListener("transactionFailed", callback => {
  console.error(callback);
});

CapacitorSquare.startTransaction({
  totalAmount: 100,
  currencyCode: "CAD",
  allowedPaymentMethods: ["CARD"],
  callbackUrl: ""
}).then(() => {
  console.log("startTransaction-success");
}).catch(e => {
  console.error(e);
});
```

The code above should log an error in the catch on the `startTransaction`. This is the Java code that is called underneath:
![image](https://user-images.githubusercontent.com/1255596/170579928-34a95c41-0145-41d2-bd35-aeebbe97b310.png)

So we are calling `openPointOfSalePlayStoreListing` if it thinks the app activity cannot be found. But we do log the error back out so the catch should return what the error is.


> I'm not sure if this matters, but do I have to have my app package name and sha-1 fingerprint setup in the square dashboard for it to open the square app instead of the app store?

We do have our fingerprints and bundle identifiers configured in Square Point of Sale API configuration although I am not sure that would be the cause of this problem.

**Comment by spycedev** [comment]
The App is definitely installed on this device.

![image](https://user-images.githubusercontent.com/83834054/170582474-a9598860-479a-49e9-9168-0ea94b8f908a.png)

**Comment by AshleyMedway** [comment]
What’s the square app version? I know there’s some kind of mapping between SDK version and app versions. We might need to log this with Square though if everything matches up.

**Comment by spycedev** [comment]
Latest version,  which I have installed is 5.91

**Comment by AshleyMedway** [comment]
Their doc just says:

> 4.64 and later

I’ll test it on my android device in the morning and raise a issue with square if I can replicate

**Comment by spycedev** [comment]
So I just tried it on an emulated Pixel_4_API_27 and it does open the square app and has the charge amount set. 
EDIT ** Not sure if this is of any help, but I also just tried setting the targetSdkVersion and compileSdkVersion to 28 it causes the app to crash. But it does not say that Square is not installed in the console.. ( maybe it doesn't have enough time to show the error)

**Comment by spycedev** [comment]
Hmm... just tried with API level 30 (highest) and it also works on an emulated device. Gonna try a few things on the real device but are you aware of anything else that needs to be done for it to work on a real device?

**Comment by spycedev** [comment]
........ Reinstalled Square POS app and it seems to work
I guess that should've been the first thing i tried.. :(

**Comment by AshleyMedway** [comment]
No worries, at least it’s sorted. Have fun with capacitor 👍
