### ISSUE TITLE
ServerTransactionId Data

### ISSUE THREAD

**Issue by spycedev** [ProteanSoftware/capacitor-square#5]
I'm sorry to bother you again. We are very close to being fully functional.
If I knew Java I'm sure I could figure this out easily, but its a little beyond me.

Is there a way we can get more details, like the transactionId, in the response from Square?

Here's my Square forum post.
https://developer.squareup.com/forums/t/transaction-data-from-clienttransactionid/6089/9

Thanks so much again for your help

**Comment by AshleyMedway** [comment]
No problem at all version 3.3.0 will return `serverTransactionId` as well as `clientTransactionId`.

Let me know if that works for you

**Comment by spycedev** [comment]
Hahah, I'm dumb sometimes. Just looked at the changed you made and its the exact same thing that I did but then I read the square documentation and it says you'll only get that id with card transactions. I was testing with cash the whole time. No wonder I wasn't getting the response I was expecting.

Thanks again

**Comment by AshleyMedway** [comment]
Ah no problem. Yeah cash transaction don't get processed on the server so there's no server transaction id.
