### ISSUE TITLE
iOS callback

### ISSUE THREAD

**Issue by spycedev** [ProteanSoftware/capacitor-square#7]
Hello,

I'm having an issue getting the IOS callback to function.

I've setup the urlScheme in the square dashboard as "courierapp" and in the startTransaction function as courierapp://payment. I've also added the urlScheme to the info.plist as "courierapp" as per the instructions.

I've gotten as far as the square app opening and processing the transaction and then our app opening back up once you click "new sale" but i'm not getting a callback response.

I think i'm just unclear on how it's supposed to work. I noted there is a handleIosResponse function but i'm not sure how to utilize that.

I've haven't change my code from our android version beside changing the things mentioned above.

What am I missing? Thanks for your help :)

**Comment by AshleyMedway** [comment]
Hey sorry I was away on holiday/vacation. let me take a look at this today :)

**Comment by AshleyMedway** [comment]
Just tested this and its working in our application.

Do you get redirected to your app but the callback code is not firing or do you not get redirected to your app at all?

I don't think its in the documentation so I'll have to get it added but we have this in our app initialized code:

```ts
App.addListener("appUrlOpen", (data: URLOpenListenerEvent) => {
  this.log.Information("iOS callback: " + data.url);

  if (data.url.toLowerCase().startsWith("app-name://callback-name")) {
    CapacitorSquare.handleIosResponse({
      url: data.url
    }).then(() => {
      this.log.Information("handle ios callback - successful");
    }).catch(x => {
      this.log.Error("handle ios callback - error - " + x);
    });
  }
});
```
Where `App` is `import { App } from "@capacitor/app";`

**Comment by spycedev** [comment]
*** Figured it our

**Comment by spycedev** [comment]
I've handled the url and got the object I need, so that's good.
I'm still interested as the what the handleIosResponse function does though, maybe I can clean up the code a bit. *** NVM - Figured it out 

Anyway, I am getting more data with iOS vs Android. With Android I'm only getting clientTransactionId but with iOS, I also get the server_transaction_id

client_transaction_id: "E471B0B5-C3CA-40AB-853E-7407E441E1BE"
status: "ok"
transaction_id: "D4XjJTM0Yylfms1w8b3SnY9eV"

And YES, this is a cash transaction.

Is there any way we can manipulate the code for android to also get this "server_transaction_id"? It does currently work debit/credit payments, but not cash.
