### ISSUE TITLE
AutoReturn & SkipReceipt

### ISSUE THREAD

**Issue by spycedev** [ProteanSoftware/capacitor-square#8]
Good day!

Not so much an issue, more so looking for help.
We've been using this plugin for a few weeks now and it's been working great.
However, due to some user issues we are hoping to "fool proof" the app a bit.

I've been able to set the autoReturn to 4 seconds as per the instructions, but it looks like there is also an option to return instantly, however, I'm haven't been successful to make that work. Most likely because I know Java :D 

Could you show me how to set that up for android?

![image](https://user-images.githubusercontent.com/83834054/184422095-97e795f9-4743-4a53-a0ac-cfd097818236.png)

**Comment by AshleyMedway** [comment]
Hey sure, this will probably require some changes to the plugin, do you have a link to the documentation you've found?

Are you still using Capacitor V3 or have you upgraded to V4?

**Comment by AshleyMedway** [comment]
I've implemented AutoReturn as per the spec for square, only for android at this time.
It is available in v3.4.1 for capacitor v3 & v4.1.1 for capacitor v4

```
autoReturnTimeout: 4000, // The timeout to set in milliseconds, or AutoReturn.NoTimeout. If you specify a timeout, it must be between 3200 milliseconds and 10000 milliseconds.
```

It doesn't say if the `NoTimeout` means immediate return or not, the doc seem to suggest the smallest allowed value is 3200 milliseconds, but give it a try :)

**Comment by spycedev** [comment]
Yeah looks like the 3200 millisecond works!

If I wanted to try immediate return, what should be the value in JS? I've tried '0' and FALSE but no luck on that. But like you said, it may not even mean immediate return. But in the iOS version you do have a "skipsReceipt" and "returnsAutomaticallyAfterPayment" arguments, so I'd so.

While were in the process of adding features, Square also allows a NOTE and Metadata to be provided, that would be super neat aswell! Thanks so much!

**Comment by spycedev** [comment]
https://developer.squareup.com/docs/api/point-of-sale/android/

Here's the link btw

**Comment by AshleyMedway** [comment]
No timeout would be a value of 0, but yeah the doc is confusing, No timeout might be the same as saying do not auto return.

I'll take a look at `skipsReceipt` we current explicitly set it to false so shouldn't be too much effort just expose it via the plugin

**Comment by AshleyMedway** [comment]
`skipsReceipt`  is available in v3.4.2 for capacitor v3 & v4.1.2 for capacitor v4

Not tested as my new Mac does not arrive until Monday

**Comment by AshleyMedway** [comment]
Again not sure how this property works, it is not documented :/

https://developer.squareup.com/docs/api/point-of-sale#sccapirequest

**Comment by spycedev** [comment]
yeah I think `skipsReceipt` works fine for iOS, will test in a minute', but I was more curious about android, I haven't been able to find anything in the docs yet. Which is silly

**Comment by spycedev** [comment]
Well I spoke with Square and they will try to implement to autoreturn and skipreceipt for android on the next release..

I did find a new issue though, that I'm not sure how to get around.. I will create a new issue thread.
